#pragma once

#include "tick_event.h"

/*! @brief Function used by modules that subscribe to the clock to receive tick events.
 *
 * Added to the pub-sub service which is then responsible for feeding those callbacks with tick 
 * events generated by the clock publisher.
 *
 *  @param[in] tick_event The tick event received.
 *  @param[in] subscriber_module Reference to the subscriber module the tick event is sent to.
 */
typedef void (*clock_subscriber_event_cb)(Tick_Event* tick_event, void* subscriber_module);
