#pragma once

#include "Game/Clock/enums.h"
#include "Game/Clock/Tick_Event/tick_event.h"


/*! @brief Function used by clock subscribers to receive tick events from the pub-sub service.
 *
 * Added to the pub-sub service which is then responsible for feeding those callbacks with tick 
 * events generated by the clock publisher.
 *
 *  @param[in] tick_event The tick event received.
 */
typedef void (*clock_subscriber_event_cb)(Tick_Event* tick_event);

typedef struct Game_Clock_Pub_Sub_Service Game_Clock_Pub_Sub_Service;

Game_Clock_Pub_Sub_Service* create_pub_sub_service();

void register_pub_sub_subscriber(
    Game_Clock_Pub_Sub_Service* service,
    clock_subscriber_event_cb subscriber_callback,
    Animation_Clock_Index animation_clock
);

void process_tick_event(Game_Clock_Pub_Sub_Service* service, Tick_Event* tick_event);

void free_pub_sub_service(Game_Clock_Pub_Sub_Service* service);